<?php

namespace Database\Seeders;

use App\Models\Program;
use App\Models\ProgramCategory;
use Illuminate\Database\Seeder;

class ProgramSeeder extends Seeder
{
    public function run(): void
    {
        $programs = [
            [
                'id' => 1,
                'category_key' => 'internasional',
                'title' => 'Program 1 Tahun + Ausbildung Jerman',
                'slug' => 'program-1-tahun-ausbildung-jerman',
                'country_badge' => 'JERMAN',
                'description' => 'Pelatihan intensif 1 tahun di kampus dilanjutkan program penempatan Ausbildung kerja di Jerman.s',
                'duration' => '1 Tahun + Ausbildung',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/international_program.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 1,
            ],
            [
                'id' => 2,
                'category_key' => 'internasional',
                'title' => 'Program 2 Tahun + 1 Semester TAFE Australia',
                'slug' => 'program-2-tahun-1-semester-tafe-australia',
                'country_badge' => 'AUSTRALIA',
                'description' => 'Studi komprehensif di Bali dengan transfer kredit 1 semester di TAFE Australia.',
                'duration' => '2 Tahun + 1 Semester',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/international_program.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 2,
            ],
            [
                'id' => 3,
                'category_key' => 'internasional',
                'title' => 'TAFE Australia Pathway',
                'slug' => 'tafe-australia-pathway',
                'country_badge' => 'AUSTRALIA',
                'description' => 'Program penyaluran langsung menuju perkuliahan TAFE di Australia.',
                'duration' => 'Pathway Program',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/hotel_lobby.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 3,
            ],
            [
                'id' => 4,
                'category_key' => 'internasional',
                'title' => 'THS Australia Pathway',
                'slug' => 'ths-australia-pathway',
                'country_badge' => 'AUSTRALIA',
                'description' => 'Jalur studi khusus berpartner dengan The Hotel School Sydney & Melbourne.',
                'duration' => 'Pathway Program',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/hotel_lobby.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 4,
            ],
            [
                'id' => 5,
                'category_key' => '2-tahun',
                'title' => 'Perhotelan (FO & HK) — 2 Tahun',
                'slug' => 'perhotelan-fo-hk-2-tahun',
                'country_badge' => '2 TAHUN',
                'description' => 'Fokus pada operasional Front Office dan Housekeeping berstandar hotel bintang 5.',
                'duration' => '2 Tahun',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/campus_students.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 1,
            ],
            [
                'id' => 6,
                'category_key' => '2-tahun',
                'title' => 'Tata Boga (Culinary Art) — 2 Tahun',
                'slug' => 'tata-boga-culinary-art-2-tahun',
                'country_badge' => '2 TAHUN',
                'description' => 'Mengembangkan keahlian memasak masakan internasional dan lokal dengan standar kebersihan tinggi.',
                'duration' => '2 Tahun',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/culinary_students.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 2,
            ],
            [
                'id' => 7,
                'category_key' => '2-tahun',
                'title' => 'Tata Hidangan (FBS & Bartender) — 2 Tahun',
                'slug' => 'tata-hidangan-fbs-bartender-2-tahun',
                'country_badge' => '2 TAHUN',
                'description' => 'Seni pelayanan makanan, minuman, mixology, dan hospitality service terapan.',
                'duration' => '2 Tahun',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/hotel_lobby.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 3,
            ],
            [
                'id' => 8,
                'category_key' => '1-tahun',
                'title' => 'Perhotelan (FO & HK) — 1 Tahun',
                'slug' => 'perhotelan-fo-hk-1-tahun',
                'country_badge' => '1 TAHUN',
                'description' => 'Teori terfokus dan penempatan praktis di Front Office & Housekeeping.',
                'duration' => '1 Tahun',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/campus_students.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 1,
            ],
            [
                'id' => 9,
                'category_key' => '1-tahun',
                'title' => 'Tata Boga (Culinary Art) — 1 Tahun',
                'slug' => 'tata-boga-culinary-art-1-tahun',
                'country_badge' => '1 TAHUN',
                'description' => 'Fondasi dasar teknik kuliner, penanganan bahan makanan, dan sanitasi.',
                'duration' => '1 Tahun',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/culinary_students.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 2,
            ],
            [
                'id' => 10,
                'category_key' => '1-tahun-kapal-pesiar',
                'title' => 'Cook (Asisten Koki) — Kapal Pesiar',
                'slug' => 'cook-asisten-koki-kapal-pesiar',
                'country_badge' => 'KAPAL PESIAR',
                'description' => 'Praktek dapur intensif untuk menyiapkan menu cruise line internasional.',
                'duration' => '1 Tahun',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/Kapal.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 1,
            ],
            [
                'id' => 11,
                'category_key' => '1-tahun-kapal-pesiar',
                'title' => 'Waiter & Bartender — Kapal Pesiar',
                'slug' => 'waiter-bartender-kapal-pesiar',
                'country_badge' => 'KAPAL PESIAR',
                'description' => 'Layanan restoran mewah & pencampuran minuman tingkat lanjut untuk bar kapal pesiar.',
                'duration' => '1 Tahun',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/international_program.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 2,
            ],
            [
                'id' => 12,
                'category_key' => '1-tahun-kapal-pesiar',
                'title' => 'Hotel Steward — Kapal Pesiar',
                'slug' => 'hotel-steward-kapal-pesiar',
                'country_badge' => 'KAPAL PESIAR',
                'description' => 'Manajemen kebersihan, tata graha, dan penataan kamar di kabin kapal pesiar mewah.',
                'duration' => '1 Tahun',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/campus_students.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 3,
            ],
            [
                'id' => 13,
                'category_key' => 'eksekutif',
                'title' => 'FBS & Bar (Cruise Line)',
                'slug' => 'fbs-bar-cruise-line',
                'country_badge' => 'EKSEKUTIF',
                'description' => 'Bonus: Free Bottle Shaker Flair untuk praktek atraksi bar.',
                'duration' => '6 Bulan',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/hotel_lobby.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 1,
            ],
            [
                'id' => 14,
                'category_key' => 'eksekutif',
                'title' => 'Cook (Cruise Line)',
                'slug' => 'cook-cruise-line',
                'country_badge' => 'EKSEKUTIF',
                'description' => 'Bonus: Free Passport & Seaman Book (Buku Pelaut) resmi.',
                'duration' => '6 Bulan',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/Kapal.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 2,
            ],
            [
                'id' => 15,
                'category_key' => 'eksekutif',
                'title' => 'Butler',
                'slug' => 'butler-eksekutif',
                'country_badge' => 'EKSEKUTIF',
                'description' => 'Pelayanan eksklusif personal. Bonus: Free Driving Licence (SIM).',
                'duration' => '6 Bulan',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/campus_students.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 3,
            ],
            [
                'id' => 16,
                'category_key' => 'eksekutif',
                'title' => 'SPA Therapist',
                'slug' => 'spa-therapist-eksekutif',
                'country_badge' => 'EKSEKUTIF',
                'description' => 'Seni pijat relaksasi dan terapi spa berkualitas hotel bintang lima.',
                'duration' => '6 Bulan',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/about_dhs.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 4,
            ],
            [
                'id' => 18,
                'category_key' => '6-bulan',
                'title' => 'Short Course F&B Service & Bar',
                'slug' => 'short-course-fbs-bar',
                'country_badge' => 'KURSUS SINGKAT',
                'description' => 'Pelatihan intensif 6 bulan F&B Service dan Bartending.',
                'duration' => '6 Bulan',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/hotel_lobby.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 1,
            ],
            [
                'id' => 19,
                'category_key' => '6-bulan',
                'title' => 'Short Course Culinary Arts',
                'slug' => 'short-course-culinary',
                'country_badge' => 'KURSUS SINGKAT',
                'description' => 'Pelatihan intensif 6 bulan dasar-dasar seni kuliner.',
                'duration' => '6 Bulan',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/short_course.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 2,
            ],
            [
                'id' => 20,
                'category_key' => '6-bulan',
                'title' => 'Short Course Housekeeping',
                'slug' => 'short-course-housekeeping',
                'country_badge' => 'KURSUS SINGKAT',
                'description' => 'Pelatihan intensif 6 bulan operasional tata graha hotel.',
                'duration' => '6 Bulan',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/campus_students.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 3,
            ],
            [
                'id' => 21,
                'category_key' => '1-tahun',
                'title' => 'Tata Hidangan (FBS & Bartender) — 1 Tahun',
                'slug' => 'tata-hidangan-fbs-bartender-1-tahun',
                'country_badge' => '1 TAHUN',
                'description' => 'Seni pelayanan makanan, minuman, mixology, dan hospitality service terapan dalam 1 tahun.',
                'duration' => '1 Tahun',
                'requirements' => NULL,
                'curriculum' => NULL,
                'facilities' => NULL,
                'thumbnail_url' => '/image/hotel_lobby.jpg',
                'brochure_url' => NULL,
                'tuition_fee' => null,
                'is_active' => true,
                'is_featured' => false,
                'display_order' => 3,
            ],
        ];

        foreach ($programs as $item) {
            $categoryKey = $item['category_key'];
            unset($item['category_key']);
            $category = ProgramCategory::where('category_key', $categoryKey)->first();
            if ($category) {
                $item['category_id'] = $category->id;
                Program::updateOrCreate(['slug' => $item['slug']], $item);
            }
        }
    }
}
